#!/usr/bin/env zsh

projs='('
for g in $(ls ~/proj)
do
    projs+=",$g"
    for p in $(ls ~/proj/$g)
    do
        projs+=",$p"
        #projs+=":$g $p"
    done
done
projs+=')'

compctl -k $projs proj
