#!/usr/bin/env zsh

if [[ 0 -eq $# ]]
then
    xproj

elif [[ 1 -eq $# ]]
then
    for d in $(ls ~/proj)
    do
        for p in $(ls ~/proj/$d)
        do
            if [[ $1 = $p ]]
            then
                if [[ -d ~/proj/$d/$p ]]
                then # directory
                    cd ~/proj/$d/$p

                else # file
                    cd ~/proj/$d
                    $EDITOR $p
                fi
                return # we did it!
            fi
        done
    done

    for d in $(ls ~/proj)
    do # in case i enter a project group, e.g. `proj zsh` should put me in ~/proj/zsh
        if [[ $1 = $d ]]
        then
            cd ~/proj/$d
            return
        fi
    done

elif [[ 2 -eq $# ]]
then
    for d in $(ls ~/proj)
    do
        if [[ $1 = $d ]]
        then
            for p in $(ls ~/proj/$d)
            do
                if [[ $2 = $p ]]
                then
                    if [[ -d ~/proj/$d/$p ]]
                    then # directory
                        cd ~/proj/$d/$p

                    else # file
                        cd ~/proj/$d
                        $EDITOR $p
                    fi
                    return # we did it!
                fi
            done
        fi
    done

elif [[ 3 -eq $# ]]
then
    if [[ "n" = $1 ]]
    then
        mkdir -p ~/proj/$2/$3
        cd ~/proj/$2/$3

    elif [[ "f" = $1 ]]
    then
        mkdir -p ~/proj/$1
        touch ~/proj/$2/$3
        cd ~/proj/$2
        $EDITOR $3
    fi
fi
